services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: cooperative-request-system-app
    container_name: cooperative-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    command: php-fpm
    volumes:
      - ./backend:/var/www
    networks:
      - cooperative-network

  web:
    image: nginx:alpine
    container_name: cooperative-web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./backend/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cooperative-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: cooperative-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: cooperative_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - cooperative-network


networks:
  cooperative-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
